version: '3.8'

services:
    mongo:
      container_name: mongodb
      image: mongo:5-focal
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${ROOT}
        MONGO_INITDB_ROOT_PASSWORD: ${PASS}
      # volumes:
      #   - mongodb-store:/data/db
      #   - mongodb-store:/data/configdb
      # networks:
      #   - mongo-compose-network  
      ports:
        - 27017:27017

    api:
      restart: always
      build: .
      ports:
        - "8000:8000"
      # command: uvicorn index:app --reload --workers 1 --host 0.0.0.0 --port 8000
      # networks:
      #   - mongo-compose-network
      volumes:
        - ./:/code:cached
      # command: [ "pytest" ] 
      links:
        - mongo

    # mongo-express:
    #   container_name: mongodb_express
    #   image: mongo-express:latest
    #   restart: always
    #   environment:
    #     ME_CONFIG_MONGODB_URL: mongodb://${ROOT}:${PASS}@mongo:${PORT}/
    #   ports:
    #     - 8081:8081
    #   depends_on: 
    #     - mongo


# volumes:
#   mongodb-store:

# networks:
#   mongo-compose-network:
#     driver: bridge     